FROM ubuntu:latest

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y nginx && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY site /var/www/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]